# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

replace_cpp <- function(x) {
    .Call(`_STPPMx_replace_cpp`, x)
}

dmvt_cpp <- function(x, v, mu, Sig) {
    .Call(`_STPPMx_dmvt_cpp`, x, v, mu, Sig)
}

partitions_draw_cpp <- function(y, X_sim, X_reg, M, alpha, c, v, s, sigma, beta, m_0, Phi, w, time_effects, space_effects, mixed_effects) {
    .Call(`_STPPMx_partitions_draw_cpp`, y, X_sim, X_reg, M, alpha, c, v, s, sigma, beta, m_0, Phi, w, time_effects, space_effects, mixed_effects)
}

partitions_draw_cpp_fast <- function(y, X_sim, X_reg, M, alpha, c, v, s, sigma, beta, m_0, Phi, w, time_effects, space_effects, mixed_effects, sizes_mem, sums_mem, products_mem) {
    .Call(`_STPPMx_partitions_draw_cpp_fast`, y, X_sim, X_reg, M, alpha, c, v, s, sigma, beta, m_0, Phi, w, time_effects, space_effects, mixed_effects, sizes_mem, sums_mem, products_mem)
}

predict_cpp_new <- function(obs, station, time, X_train_sim, x_futur_sim, x_futur_reg, y_test, beta_list, sigma_list, space_effects_list, time_effects_list, mixed_effects_list, clusters_sizes_list, partition_list, alpha_vec, nb_density, nb_draw, w, Phi, v, s, m_0) {
    .Call(`_STPPMx_predict_cpp_new`, obs, station, time, X_train_sim, x_futur_sim, x_futur_reg, y_test, beta_list, sigma_list, space_effects_list, time_effects_list, mixed_effects_list, clusters_sizes_list, partition_list, alpha_vec, nb_density, nb_draw, w, Phi, v, s, m_0)
}

solve_cpp <- function(M, symmetric) {
    .Call(`_STPPMx_solve_cpp`, M, symmetric)
}

spsolve_cpp <- function(M) {
    .Call(`_STPPMx_spsolve_cpp`, M)
}

kronecker_cpp <- function(M, Q) {
    .Call(`_STPPMx_kronecker_cpp`, M, Q)
}

spkronecker_cpp <- function(M, Q) {
    .Call(`_STPPMx_spkronecker_cpp`, M, Q)
}

